stages:
  - test
  - deploy

default:
  interruptible: true

test:
  stage: test
  image: node:22-alpine
  script:
    - npm ci
    - npm test
    - npm run build
  cache:
    paths:
      - node_modules/
  only:
    - merge_requests
    - main
  tags:
    - shared

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker compose -p express1 up -d --remove-orphans --build --force-recreate
