services:
  api:
    build: .
    ports:
      - "3000:3000"
    container_name: expressjs-backend
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=/data/express1.db
    volumes:
      - dbdata:/data

volumes:
  dbdata:
